### ISSUE TITLE
Login: preprend `https://` to the url

### ISSUE THREAD

**Issue by thhck** [NoelDeMartin/aerogel#1]
Hello !
I was having fun in the aerogel playground and when trying to use the login at https://aerogel.js.org/playground/solid I lazily inserted `solidcommunity.net` and got an error. 
Would  it be possible to prepend the protocol by default if not given by the user ?

**Comment by NoelDeMartin** [comment]
Hey, thanks for checking it out and giving some feedback :).

Yes, I am actually doing that in some of my apps as well, so it's a good idea to implement it here as well.

**Comment by NoelDeMartin** [comment]
Fixed and deployed!
